#Testing SQL Script By gykerk 20231028
SELECT 
    TO_CHAR(DATE, 'YYYY-MM') AS Month,
    SUM(VOLUME) AS Total_Volume
FROM BIGDATA228.STOCKSCHEMA.MERGED_STOCKDATA
WHERE SYMBOL = 'GOOG'
AND (DATE >= TO_DATE('2023-01-01') AND DATE < TO_DATE('2023-02-01')
    OR DATE >= TO_DATE('2023-02-01') AND DATE < TO_DATE('2023-03-01'))
GROUP BY Month;

SELECT SUM(ai_out) AS "预计总销售额"
FROM BIZMASTERDB.SALESSCHEMA.SALESFACTTB
WHERE STATE = 'California' 

AND DATE_TRUNC('YEAR', ORDERDATE) = '2024-01-01'

SELECT COUNTRY, SUM(AI_OUT) AS PREDICTED_NEXT_QUARTER_SALES
FROM BIZMASTERDB.SALESSCHEMA.SALESFACTTB
WHERE ORDERDATE > GETDATE() AND ORDERDATE <= ADD_MONTHS(GETDATE(), 3)
GROUP BY COUNTRY
select GETDATE() ,ADD_MONTHS(GETDATE(), 3)

SELECT SUM(ai_out) AS total_predicted_sales
FROM BIZMASTERDB.SALESSCHEMA.SALESFACTTB
WHERE ORDERDATE >= '2024-01-01' AND ORDERDATE <= '2024-12-31'
AND CITY = 'Beijing';

GROUP BY COUNTRY